### PR TITLE
Remove firefox extension file and screenshot

### PR DESCRIPTION
**Pull request by dimspith**
Firefox seems to be changing things on the UI recently and the initial xpi extension file is deprecated. Since everyone installs extensions from the Firefox Addons store i think it would be best if people are lead to install it from there and the xpi file be removed. It's also easier on me to maintain the extension if future changes occur.

### CODE REVIEW

**Comment by FrenzyExists** [comment]
I think its good if a Mountain theme is just put in the store and a link is dropped in the repo

**Comment by pradyungn** [comment]
Hmmm i think that's a good idea - i'll merge in this commit for now and we can put up something in the Firefox store in the future?

**Comment by FrenzyExists** [comment]
Yeah, prolly a discussion section bout the Firefox Store would be good. Firefox has its own theme generator, as well as there's a theme generator around:

- https://color.firefox.com/

- https://extensionworkshop.com/documentation/themes/using-the-amo-theme-generator

It could be a start i guess

**Comment by dimspith** [comment]
> Yeah, prolly a discussion section bout the Firefox Store would be good. Firefox has its own theme generator, as well as there's a theme generator around:
> 
>     * https://color.firefox.com/
> 
>     * https://extensionworkshop.com/documentation/themes/using-the-amo-theme-generator
> 
> 
> It could be a start i guess

The theme is ready though, you can see it in the link i put on the firefox section of the repo.
I used firefox color for this too. If you have any questions or improvements feel free to let me know.

**Pull request merged**
