### PR TITLE
Add Wezterm theme!

### PR DESCRIPTION
**Pull request by aadisang**
Lemme know if some of the color variables should be changed.

### CODE REVIEW

**Comment by pradyungn** [comment]
Hmmm instructions seem to be for duckduckgo, not wezterm... can that be fixed?

**Comment by pradyungn** [comment]
oh wait i read the wrong readme lol. lgtm!

**Comment by pradyungn** [comment]
hey, check your bright/ansi colors in the toml file - they look mostly the same? check the Fuji reference to get the relevant color palette.

**Comment by aadisang** [comment]
How's that looking?

**Comment by pradyungn** [comment]
sorry about the late response - looks fine!

**Pull request merged**
